workflow:
  rules:
    - if: $CI_COMMIT_BRANCH
install_dependencies:
  stage: build
  script:
    - echo "This is the installation step"
before_script:
  - >-
    CONTAINER NAME="affectionate_saha" if docker ps -a --format "{{.Names}}" |
    grep -q "^$CONTAINER NAMES"; then echo "Stopping existing container..."
    docker stop $CONTAINER NAME docker rm $CONTAINER_NAME

    fi
test:
  stage: test
  script:
    - 'docker run -d --name $CONTAINER NAME -v $(pwd)/public/:/usr/local/apache2/htdocs/ -p 9080:80 httpd': latest
  artifact: null
  paths:
    - public/
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
